export const REGISTER_REQUEST = 'USERS_REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'USERS_REGISTER_FAILURE';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';


export const INIT_MESSAGE = ' INIT_MESSAGE';
export const COMPOSE_MESSAGE = 'COMPOSE_MESSAGE';
export const MESSAGE_SENT = 'MESSAGE_SENT';
export const MESSAGE_FAILURE = 'MESSAGE_FAILURE';
export const MESSAGE_NOT_SENT = 'MESSAGE_NOT_SENT';
export const END_COMPOSE_MESSAGE = 'END_COMPOSE_MESSAGE';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const GET_MESSAGES = 'GET_MESSAGES';

export const LOGOUT = 'USERS_LOGOUT';
